services:
  postgres:
    image: postgres
    shm_size: 128mb
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - PGDATA='/var/lib/postgresql/data/pgdata'
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"
    restart: always
  memcached:
    image: memcached:latest
    ports:
      - "11212:11211"
    restart: always
  gayatriapp:
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - django_logs:/logs
    build:
      context: ./gayatri_invoice
    environment:
      - DJANGO_SETTINGS_MODULE:${DJANGO_SETTINGS_MODULE}
      - DJANGO_SECRET_KEY:${DJANGO_SECRET_KEY}
      - DEBUG:${DEBUG}
      - DJANGO_LOG_LEVEL:${DJANGO_LOG_LEVEL}
      - DJANGO_ALLOWED_HOSTS:${DJANGO_ALLOWED_HOSTS}
      - DATABASE_NAME:${DATABASE_NAME}
      - DATABASE_USERNAME:${DATABASE_USERNAME}
      - DATABASE_PASSWORD:${DATABASE_PASSWORD}
      - DATABASE_HOST:${DATABASE_HOST}
      - DATABASE_PORT:${DATABASE_PORT}
      - TEST:${TEST}
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - postgres
      - memcached
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/default.conf:/nginx/default.conf
    depends_on:
      - gayatriapp
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/invoice"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  static_volume:
  media_volume:
  postgres_db:
  django_logs:
