pipeline {
	agent {
		docker {
			image 'python:3.13.2-alpine3.21'
		}
	}
	triggers {
		githubPush()
	}
	stages {
		stage('build') {
			steps {
				sh 'export HOME=$WORKSPACE'
				sh 'pip install --user pipx'
				sh 'pipx ensurepath'
				sh 'pipx install -r cicd/requirements.txt'
			}
		}
	}
}
