pipeline {
	agent any
	triggers {
		githubPush()
	}
	agent {
		docker {
			image 'python:3.13.2-alpine3.21'
		}
	}
	stages {
		stage('build') {
			steps {
				sh 'python3 -m pip install --user pipx'
				sh 'python3 -m pipx ensurepath'
				sh 'pipx install -r cicd/requirements.txt'
			}
		}
	}
}
