# Generated by Django 4.2.16 on 2024-11-26 12:33

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_adminprofile_admindraftforms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('formName', models.CharField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hasAccess', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
