# Generated by Django 4.2.15 on 2024-08-13 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='AdminDraftForms',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userForms',
        ),
        migrations.AddField(
            model_name='profile',
            name='userPass',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
