pipeline {
	agent any
	environment {
		COMPOSE_FILE = 'docker-compose.yml'
	}
	stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Copy Environment File') {
			steps {
				// Copy the .env file from Jenkins credentials
				withCredentials([file(credentialsId: '5abd70f6-4458-4060-b14e-9e2445bf15df, variable: 'ENV_FILE')]) {
					sh 'cp $ENV_FILE .env'
				}
				sh 'echo "Environment file copied successfully"'
			}
		}
		stage('Install Dependencies with Poetry') {
			steps {
				dir('gayatri_invoice') {
					sh '''
					pipx install poetry
					pipx ensurepath
					export PATH="$HOME/.local/bin:$PATH"
					poetry install
					'''
				}
			}
		}
		// Placeholder for future tests
		// stage('Run Django Tests') {
		//     steps {
		//         dir('gayatri_invoice') {
		//             sh 'docker-compose run --rm gayatriapp python manage.py test'
		//         }
		//     }
		// }
		stage('Build Docker Images') {
			steps {
				sh 'docker-compose build'
			}
		}
		stage('Collect Static Files') {
			steps {
				sh 'docker-compose run --rm gayatriapp python manage.py collectstatic --noinput'
			}
		}
		stage('Migrate Database') {
			steps {
				sh 'docker-compose run --rm gayatriapp python manage.py migrate'
			}
		}
		stage('Deploy') {
			steps {
				sh 'docker-compose up -d --build'
			}
		}
	}
	post {
		always {
			sh 'mkdir -p cicd && docker-compose logs > cicd/deploy.log || true'
		}
	}
}
