--
-- PostgreSQL database dump
--

\restrict bFnjweCAIxzbDExZ5kkcpIGfM1njrIhHjVraeFJckiMCvISz8xg5FAkGdCPlnTt

-- Dumped from database version 17.6 (Debian 17.6-0+deb13u1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: invoice_company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_company (
    id bigint NOT NULL,
    company_name character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.invoice_company OWNER TO postgres;

--
-- Name: invoice_company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    user_name character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    user_emp_code character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    is_admin boolean NOT NULL,
    company_id bigint
);


ALTER TABLE public.invoice_customuser OWNER TO postgres;

--
-- Name: invoice_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.invoice_customuser_groups OWNER TO postgres;

--
-- Name: invoice_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.invoice_customuser_user_permissions OWNER TO postgres;

--
-- Name: invoice_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_form; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_form (
    id bigint NOT NULL,
    form_name character varying NOT NULL,
    form_data jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.invoice_form OWNER TO postgres;

--
-- Name: invoice_form_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_form_group (
    id bigint NOT NULL,
    form_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.invoice_form_group OWNER TO postgres;

--
-- Name: invoice_form_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_form_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_form_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_form_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_form_table (
    id bigint NOT NULL,
    form_id bigint NOT NULL,
    tablename_id bigint NOT NULL
);


ALTER TABLE public.invoice_form_table OWNER TO postgres;

--
-- Name: invoice_form_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_form_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_form_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_report (
    id bigint NOT NULL,
    report_name character varying NOT NULL,
    report_data jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.invoice_report OWNER TO postgres;

--
-- Name: invoice_report_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_report_group (
    id bigint NOT NULL,
    report_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.invoice_report_group OWNER TO postgres;

--
-- Name: invoice_report_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_report_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_report_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_report_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_report_table (
    id bigint NOT NULL,
    report_id bigint NOT NULL,
    tablename_id bigint NOT NULL
);


ALTER TABLE public.invoice_report_table OWNER TO postgres;

--
-- Name: invoice_report_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_report_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_report_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_tabledata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_tabledata (
    id bigint NOT NULL,
    table_data jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL,
    table_name_id bigint NOT NULL
);


ALTER TABLE public.invoice_tabledata OWNER TO postgres;

--
-- Name: invoice_tabledata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_tabledata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_tabledata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_tablemetadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_tablemetadata (
    id bigint NOT NULL,
    table_metadata jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    table_name_id bigint NOT NULL
);


ALTER TABLE public.invoice_tablemetadata OWNER TO postgres;

--
-- Name: invoice_tablemetadata_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_tablemetadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_tablemetadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_tablename; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_tablename (
    id bigint NOT NULL,
    table_name character varying(255),
    description character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.invoice_tablename OWNER TO postgres;

--
-- Name: invoice_tablename_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_tablename ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_tablename_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_template (
    id bigint NOT NULL,
    template_name character varying NOT NULL,
    file_type character varying NOT NULL,
    file_data character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.invoice_template OWNER TO postgres;

--
-- Name: invoice_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	admin
2	user
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	1	1
2	1	2
3	1	3
4	1	4
5	1	5
6	1	6
7	1	7
8	1	8
9	1	9
10	1	10
11	1	11
12	1	12
13	1	13
14	1	14
15	1	15
16	1	16
17	1	17
18	1	18
19	1	19
20	1	20
21	1	21
22	1	22
23	1	23
24	1	24
25	1	25
26	1	26
27	1	27
28	1	28
29	1	29
30	1	30
31	1	31
32	1	32
33	1	33
34	1	34
35	1	35
36	1	36
37	1	37
38	1	38
39	1	39
40	1	40
41	1	41
42	1	42
43	1	43
44	1	44
45	1	45
46	1	46
47	1	47
48	1	48
49	1	49
50	1	50
51	1	51
52	1	52
53	1	53
54	1	54
55	2	4
56	2	8
57	2	12
58	2	16
59	2	20
60	2	54
61	2	24
62	2	26
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add company	1	add_company
2	Can change company	1	change_company
3	Can delete company	1	delete_company
4	Can view company	1	view_company
5	Can add table name	2	add_tablename
6	Can change table name	2	change_tablename
7	Can delete table name	2	delete_tablename
8	Can view table name	2	view_tablename
9	Can add table meta data	3	add_tablemetadata
10	Can change table meta data	3	change_tablemetadata
11	Can delete table meta data	3	delete_tablemetadata
12	Can view table meta data	3	view_tablemetadata
13	Can add table data	4	add_tabledata
14	Can change table data	4	change_tabledata
15	Can delete table data	4	delete_tabledata
16	Can view table data	4	view_tabledata
17	Can add Report	5	add_report
18	Can change Report	5	change_report
19	Can delete Report	5	delete_report
20	Can view Report	5	view_report
21	Can add Form	6	add_form
22	Can change Form	6	change_form
23	Can delete Form	6	delete_form
24	Can view Form	6	view_form
25	can edit form	6	edit_form
26	can access form	6	access_form
27	Can add User	7	add_customuser
28	Can change User	7	change_customuser
29	Can delete User	7	delete_customuser
30	Can view User	7	view_customuser
31	Can add Template	8	add_template
32	Can change Template	8	change_template
33	Can delete Template	8	delete_template
34	Can view Template	8	view_template
35	Can add log entry	9	add_logentry
36	Can change log entry	9	change_logentry
37	Can delete log entry	9	delete_logentry
38	Can view log entry	9	view_logentry
39	Can add permission	10	add_permission
40	Can change permission	10	change_permission
41	Can delete permission	10	delete_permission
42	Can view permission	10	view_permission
43	Can add group	11	add_group
44	Can change group	11	change_group
45	Can delete group	11	delete_group
46	Can view group	11	view_group
47	Can add content type	12	add_contenttype
48	Can change content type	12	change_contenttype
49	Can delete content type	12	delete_contenttype
50	Can view content type	12	view_contenttype
51	Can add session	13	add_session
52	Can change session	13	change_session
53	Can delete session	13	delete_session
54	Can view session	13	view_session
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-30 17:24:41.780341+05:30	1	admin	1	[{"added": {}}]	11	1
2	2025-10-30 17:25:44.135279+05:30	2	user	1	[{"added": {}}]	11	1
3	2025-10-30 17:25:52.641583+05:30	1	GSPBL	1	[{"added": {}}]	1	1
4	2025-10-30 17:25:55.80489+05:30	2	KPM	1	[{"added": {}}]	1	1
5	2025-10-30 17:25:57.688242+05:30	3	TISSUE	1	[{"added": {}}]	1	1
6	2025-10-30 17:25:59.993311+05:30	4	UNIT 1	1	[{"added": {}}]	1	1
7	2025-10-30 17:26:03.572038+05:30	5	UNIT 2	1	[{"added": {}}]	1	1
8	2025-10-30 17:26:14.699661+05:30	1	57	2	[{"changed": {"fields": ["company", "groups"]}}]	7	1
9	2025-10-30 17:26:40.149857+05:30	2	01	1	[{"added": {}}]	7	1
10	2025-10-30 17:27:38.328667+05:30	2	01	2	[{"changed": {"fields": ["company", "Is staff"]}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	invoice	company
2	invoice	tablename
3	invoice	tablemetadata
4	invoice	tabledata
5	invoice	report
6	invoice	form
7	invoice	customuser
8	invoice	template
9	admin	logentry
10	auth	permission
11	auth	group
12	contenttypes	contenttype
13	sessions	session
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-30 17:23:23.338733+05:30
2	contenttypes	0002_remove_content_type_name	2025-10-30 17:23:23.344599+05:30
3	auth	0001_initial	2025-10-30 17:23:23.399078+05:30
4	auth	0002_alter_permission_name_max_length	2025-10-30 17:23:23.402947+05:30
5	auth	0003_alter_user_email_max_length	2025-10-30 17:23:23.408042+05:30
6	auth	0004_alter_user_username_opts	2025-10-30 17:23:23.412176+05:30
7	auth	0005_alter_user_last_login_null	2025-10-30 17:23:23.417375+05:30
8	auth	0006_require_contenttypes_0002	2025-10-30 17:23:23.418721+05:30
9	auth	0007_alter_validators_add_error_messages	2025-10-30 17:23:23.424047+05:30
10	auth	0008_alter_user_username_max_length	2025-10-30 17:23:23.428201+05:30
11	auth	0009_alter_user_last_name_max_length	2025-10-30 17:23:23.433299+05:30
12	auth	0010_alter_group_name_max_length	2025-10-30 17:23:23.438186+05:30
13	auth	0011_update_proxy_permissions	2025-10-30 17:23:23.443261+05:30
14	auth	0012_alter_user_first_name_max_length	2025-10-30 17:23:23.447442+05:30
15	invoice	0001_initial	2025-10-30 17:23:23.598062+05:30
16	admin	0001_initial	2025-10-30 17:23:23.617769+05:30
17	admin	0002_logentry_remove_auto_add	2025-10-30 17:23:23.624101+05:30
18	admin	0003_logentry_add_action_flag_choices	2025-10-30 17:23:23.631552+05:30
19	invoice	0002_template_alter_customuser_user_name	2025-10-30 17:23:23.647162+05:30
20	sessions	0001_initial	2025-10-30 17:23:23.653598+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
z52176tzo1ehpdl6k6cubv5ecv01s5e6	.eJxVjsEOgjAQRP-lZ9NAadnWo3e_oWl3t4IiNRQOxvjvguGg13kzL_MSPixz55fCk-9JHEUtDr9ZDHjjcQN0DeMlS8zjPPVRbhW50yLPmXg47d0_QRdKt64DamgTsapsUhATAzQtmhgcgoHWUARIzulkLDY2VaStU7pmimSUs9UqLTwwzkwe8_0Rxuf3r3l_AKIHQKs:1vF3zA:2TpnZ-GTylo8H4xE0Ye7DYEI6uvRJMulKJzzhlC0Sm4	2025-11-15 10:47:08.552361+05:30
1csc38eyp37q2m4lywvgyya4gpymky4h	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFoqE:Gk8AF1t2s7DWozeBPAJRE8Bp9jBB_i6_Q5I1kbkkpjE	2025-11-17 12:49:02.46734+05:30
bnt9fupmnvw3byqmmzn6ee1dkfz6ry2k	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFp3X:wpnFf-lEqOMHR1xhzTXCnTQXwEJsqYuzhm6aqBy1NQY	2025-11-17 13:02:47.19137+05:30
u4k2ix3jqsyjbvugohyi7c1fn5h61rvt	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFp4Q:7aOZrk6C_R9sCoaj-M2H-n7hV9BXXcetVPjh-3LWD5s	2025-11-17 13:03:42.438283+05:30
o2wnee9o2v60mkwhc7movbgz3ykian91	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFpBA:Q_Ewo6Gqa9ROT8kQhRrXMDm2JYfOn5rDV3KaZNPwbd0	2025-11-17 13:10:40.458261+05:30
a7tv1q8ll7yiia092fe8steveb6odg20	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFpEN:hZ133i8r6rXgqTfGGAN-ve_alR1lI9oKpqUuA_u_DpM	2025-11-17 13:13:59.543352+05:30
eslwxmekd3h6rhdp762nozi0d5ni531g	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFpEv:pHpgq9qwWQkyKrECv1ra_64WfGSe8CGSl5pW5vry3Bg	2025-11-17 13:14:33.880844+05:30
4s6t8f2xf2vbv0osipl5we9mxk73d4ik	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFpHF:-FinlUDfHenCQZmCs1GFuAsUidpETw8JrycDLueJNPo	2025-11-17 13:16:57.610087+05:30
iuhtpe2u1msjgeh4qj33s08kecy6ctif	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vFqrQ:binqM-Qta7emsLawkn6rm3VpAQyIPxe-xl4ImY3AEcA	2025-11-17 14:58:24.609456+05:30
8olg8q9vksf6m9vpc19djkei5dlfaf7e	.eJxVjEEOwiAQRe_C2hBKgQGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTiLQZx-t4T5wW0HdMd2m2We27pMSe6KPGiX15n4eTncv4OKvX5rzAZcIdbKFw2pMMDosk0YMlhwlhJACcEU6_PoiyLjgzYDUyKrg1fi_QH2-zgB:1vGwY5:6KMwN9ZPBQ4nclJ8Wb4gE6stZROABN1nOY0VtNcrG9g	2025-11-20 15:14:57.643444+05:30
\.


--
-- Data for Name: invoice_company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_company (id, company_name, created_at, updated_at) FROM stdin;
1	GSPBL	2025-10-30 17:25:52.640003+05:30	2025-10-30 17:25:52.640016+05:30
2	KPM	2025-10-30 17:25:55.803399+05:30	2025-10-30 17:25:55.803419+05:30
3	TISSUE	2025-10-30 17:25:57.68679+05:30	2025-10-30 17:25:57.686808+05:30
4	UNIT 1	2025-10-30 17:25:59.991524+05:30	2025-10-30 17:25:59.991542+05:30
5	UNIT 2	2025-10-30 17:26:03.570774+05:30	2025-10-30 17:26:03.570796+05:30
\.


--
-- Data for Name: invoice_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_customuser (id, password, last_login, user_name, email, user_emp_code, created_at, updated_at, is_superuser, is_staff, is_active, is_admin, company_id) FROM stdin;
2	pbkdf2_sha256$1000000$z3bUsuXzWsjw35R6u05T8o$Fgz/DUtlD+NF/j3mWcZd6ORCE/p2cuQJmQpmau+m+gg=	2025-11-06 15:14:05.813314+05:30	test	testuser@gmail.com	01	2025-10-30 17:26:40.137512+05:30	2025-10-30 17:27:38.324928+05:30	f	t	t	f	5
1	pbkdf2_sha256$1000000$DRDCKImwVsoUHeK0SHrtZm$LX+UCmJM/n76Q6gMwHiyqmL9KNT2A0FtF2DbaBGSTKk=	2025-11-06 15:14:57.628863+05:30	nixon	nixonnelson22@gmail.com	57	2025-10-30 17:24:13.253288+05:30	2025-10-30 17:26:14.696535+05:30	t	t	t	t	5
\.


--
-- Data for Name: invoice_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_customuser_groups (id, customuser_id, group_id) FROM stdin;
1	1	1
2	2	2
\.


--
-- Data for Name: invoice_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: invoice_form; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_form (id, form_name, form_data, created_at, updated_at, company_id) FROM stdin;
\.


--
-- Data for Name: invoice_form_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_form_group (id, form_id, group_id) FROM stdin;
\.


--
-- Data for Name: invoice_form_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_form_table (id, form_id, tablename_id) FROM stdin;
\.


--
-- Data for Name: invoice_report; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_report (id, report_name, report_data, created_at, updated_at, company_id) FROM stdin;
\.


--
-- Data for Name: invoice_report_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_report_group (id, report_id, group_id) FROM stdin;
\.


--
-- Data for Name: invoice_report_table; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_report_table (id, report_id, tablename_id) FROM stdin;
\.


--
-- Data for Name: invoice_tabledata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_tabledata (id, table_data, created_at, updated_at, company_id, table_name_id) FROM stdin;
1	{"city": "mira-bhayandar", "state": "Maharashtra", "gst_no": "asdasdasdas1231", "pan_no": "asdasdasda", "district": "asdasd", "pin_code": 401101, "dispatch_to": "asdasd", "invoice_type": "local", "payment_term": 3, "customer_name": "nixon", "address_details": "green view, bhayandar", "agent_or_customer_name": "nixon"}	2025-10-30 17:43:28.469795+05:30	2025-10-30 17:43:28.496208+05:30	5	1
\.


--
-- Data for Name: invoice_tablemetadata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_tablemetadata (id, table_metadata, created_at, updated_at, table_name_id) FROM stdin;
1	{"city": "str", "state": "str", "gst_no": "str", "pan_no": "str", "district": "str", "pin_code": "int", "dispatch_to": "str", "invoice_type": "str", "payment_term": "int", "customer_name": "str", "address_details": "str", "agent_or_customer_name": "str"}	2025-10-30 17:42:45.60852+05:30	2025-10-30 17:42:45.608531+05:30	1
2	{"city": "str", "state": "str", "gst_no": "str", "pan_no": "str", "district": "str", "pin_code": "int", "dispatch_to": "str", "invoice_type": "str", "payment_term": "int", "supplier_name": "str", "agent _or_supplier_name": "str"}	2025-10-30 17:46:52.8746+05:30	2025-10-30 17:46:52.874613+05:30	2
\.


--
-- Data for Name: invoice_tablename; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_tablename (id, table_name, description, created_at, updated_at, company_id) FROM stdin;
1	customer	customer and agent  info	2025-10-30 17:42:45.583691+05:30	2025-10-30 17:42:45.583703+05:30	5
2	supplier	supplier info	2025-10-30 17:46:52.870692+05:30	2025-10-30 17:46:52.870704+05:30	5
\.


--
-- Data for Name: invoice_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_template (id, template_name, file_type, file_data, created_at, updated_at) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 62, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 54, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 10, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: invoice_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_company_id_seq', 5, true);


--
-- Name: invoice_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_customuser_groups_id_seq', 2, true);


--
-- Name: invoice_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_customuser_id_seq', 2, true);


--
-- Name: invoice_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_customuser_user_permissions_id_seq', 1, false);


--
-- Name: invoice_form_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_form_group_id_seq', 1, false);


--
-- Name: invoice_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_form_id_seq', 1, false);


--
-- Name: invoice_form_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_form_table_id_seq', 1, false);


--
-- Name: invoice_report_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_report_group_id_seq', 1, false);


--
-- Name: invoice_report_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_report_id_seq', 1, false);


--
-- Name: invoice_report_table_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_report_table_id_seq', 1, false);


--
-- Name: invoice_tabledata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_tabledata_id_seq', 2, true);


--
-- Name: invoice_tablemetadata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_tablemetadata_id_seq', 2, true);


--
-- Name: invoice_tablename_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_tablename_id_seq', 2, true);


--
-- Name: invoice_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.invoice_template_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: invoice_company invoice_company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_company
    ADD CONSTRAINT invoice_company_pkey PRIMARY KEY (id);


--
-- Name: invoice_customuser_groups invoice_customuser_groups_customuser_id_group_id_38f2e625_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_groups
    ADD CONSTRAINT invoice_customuser_groups_customuser_id_group_id_38f2e625_uniq UNIQUE (customuser_id, group_id);


--
-- Name: invoice_customuser_groups invoice_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_groups
    ADD CONSTRAINT invoice_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: invoice_customuser invoice_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser
    ADD CONSTRAINT invoice_customuser_pkey PRIMARY KEY (id);


--
-- Name: invoice_customuser_user_permissions invoice_customuser_user__customuser_id_permission_3a59358e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_user_permissions
    ADD CONSTRAINT invoice_customuser_user__customuser_id_permission_3a59358e_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: invoice_customuser invoice_customuser_user_emp_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser
    ADD CONSTRAINT invoice_customuser_user_emp_code_key UNIQUE (user_emp_code);


--
-- Name: invoice_customuser_user_permissions invoice_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_user_permissions
    ADD CONSTRAINT invoice_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: invoice_form_group invoice_form_group_form_id_group_id_c51d0fb4_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_group
    ADD CONSTRAINT invoice_form_group_form_id_group_id_c51d0fb4_uniq UNIQUE (form_id, group_id);


--
-- Name: invoice_form_group invoice_form_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_group
    ADD CONSTRAINT invoice_form_group_pkey PRIMARY KEY (id);


--
-- Name: invoice_form invoice_form_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form
    ADD CONSTRAINT invoice_form_pkey PRIMARY KEY (id);


--
-- Name: invoice_form_table invoice_form_table_form_id_tablename_id_20cf52ef_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_table
    ADD CONSTRAINT invoice_form_table_form_id_tablename_id_20cf52ef_uniq UNIQUE (form_id, tablename_id);


--
-- Name: invoice_form_table invoice_form_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_table
    ADD CONSTRAINT invoice_form_table_pkey PRIMARY KEY (id);


--
-- Name: invoice_report_group invoice_report_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_group
    ADD CONSTRAINT invoice_report_group_pkey PRIMARY KEY (id);


--
-- Name: invoice_report_group invoice_report_group_report_id_group_id_b3f0680a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_group
    ADD CONSTRAINT invoice_report_group_report_id_group_id_b3f0680a_uniq UNIQUE (report_id, group_id);


--
-- Name: invoice_report invoice_report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report
    ADD CONSTRAINT invoice_report_pkey PRIMARY KEY (id);


--
-- Name: invoice_report_table invoice_report_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_table
    ADD CONSTRAINT invoice_report_table_pkey PRIMARY KEY (id);


--
-- Name: invoice_report_table invoice_report_table_report_id_tablename_id_c10f15fb_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_table
    ADD CONSTRAINT invoice_report_table_report_id_tablename_id_c10f15fb_uniq UNIQUE (report_id, tablename_id);


--
-- Name: invoice_tabledata invoice_tabledata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tabledata
    ADD CONSTRAINT invoice_tabledata_pkey PRIMARY KEY (id);


--
-- Name: invoice_tabledata invoice_tabledata_table_data_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tabledata
    ADD CONSTRAINT invoice_tabledata_table_data_key UNIQUE (table_data);


--
-- Name: invoice_tablemetadata invoice_tablemetadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablemetadata
    ADD CONSTRAINT invoice_tablemetadata_pkey PRIMARY KEY (id);


--
-- Name: invoice_tablemetadata invoice_tablemetadata_table_metadata_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablemetadata
    ADD CONSTRAINT invoice_tablemetadata_table_metadata_key UNIQUE (table_metadata);


--
-- Name: invoice_tablename invoice_tablename_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablename
    ADD CONSTRAINT invoice_tablename_pkey PRIMARY KEY (id);


--
-- Name: invoice_template invoice_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_template
    ADD CONSTRAINT invoice_template_pkey PRIMARY KEY (id);


--
-- Name: invoice_tabledata unique_table_data_name_company; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tabledata
    ADD CONSTRAINT unique_table_data_name_company UNIQUE (table_data, table_name_id, company_id);


--
-- Name: invoice_tablemetadata unique_table_metadata_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablemetadata
    ADD CONSTRAINT unique_table_metadata_name UNIQUE (table_metadata, table_name_id);


--
-- Name: invoice_tablename unique_table_name_company; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablename
    ADD CONSTRAINT unique_table_name_company UNIQUE (table_name, company_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: invoice_cus_email_9d532c_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_cus_email_9d532c_idx ON public.invoice_customuser USING btree (email);


--
-- Name: invoice_cus_user_em_161fc6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_cus_user_em_161fc6_idx ON public.invoice_customuser USING btree (user_emp_code);


--
-- Name: invoice_customuser_company_id_73c4c12b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_company_id_73c4c12b ON public.invoice_customuser USING btree (company_id);


--
-- Name: invoice_customuser_groups_customuser_id_369028c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_groups_customuser_id_369028c2 ON public.invoice_customuser_groups USING btree (customuser_id);


--
-- Name: invoice_customuser_groups_group_id_d90819a4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_groups_group_id_d90819a4 ON public.invoice_customuser_groups USING btree (group_id);


--
-- Name: invoice_customuser_user_emp_code_8af57b16_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_user_emp_code_8af57b16_like ON public.invoice_customuser USING btree (user_emp_code varchar_pattern_ops);


--
-- Name: invoice_customuser_user_permissions_customuser_id_14ed4fcc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_user_permissions_customuser_id_14ed4fcc ON public.invoice_customuser_user_permissions USING btree (customuser_id);


--
-- Name: invoice_customuser_user_permissions_permission_id_a94c7860; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_customuser_user_permissions_permission_id_a94c7860 ON public.invoice_customuser_user_permissions USING btree (permission_id);


--
-- Name: invoice_form_company_id_4ada5fcd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_form_company_id_4ada5fcd ON public.invoice_form USING btree (company_id);


--
-- Name: invoice_form_group_form_id_fac11931; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_form_group_form_id_fac11931 ON public.invoice_form_group USING btree (form_id);


--
-- Name: invoice_form_group_group_id_1ca5d9f1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_form_group_group_id_1ca5d9f1 ON public.invoice_form_group USING btree (group_id);


--
-- Name: invoice_form_table_form_id_1e30177e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_form_table_form_id_1e30177e ON public.invoice_form_table USING btree (form_id);


--
-- Name: invoice_form_table_tablename_id_a252126a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_form_table_tablename_id_a252126a ON public.invoice_form_table USING btree (tablename_id);


--
-- Name: invoice_report_company_id_07f257b0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_report_company_id_07f257b0 ON public.invoice_report USING btree (company_id);


--
-- Name: invoice_report_group_group_id_fa22ca7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_report_group_group_id_fa22ca7d ON public.invoice_report_group USING btree (group_id);


--
-- Name: invoice_report_group_report_id_98b15249; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_report_group_report_id_98b15249 ON public.invoice_report_group USING btree (report_id);


--
-- Name: invoice_report_table_report_id_f7d87d1e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_report_table_report_id_f7d87d1e ON public.invoice_report_table USING btree (report_id);


--
-- Name: invoice_report_table_tablename_id_6ab6dab9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_report_table_tablename_id_6ab6dab9 ON public.invoice_report_table USING btree (tablename_id);


--
-- Name: invoice_tabledata_company_id_c13f0549; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_tabledata_company_id_c13f0549 ON public.invoice_tabledata USING btree (company_id);


--
-- Name: invoice_tabledata_table_name_id_56bd5706; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_tabledata_table_name_id_56bd5706 ON public.invoice_tabledata USING btree (table_name_id);


--
-- Name: invoice_tablemetadata_table_name_id_025ada4e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_tablemetadata_table_name_id_025ada4e ON public.invoice_tablemetadata USING btree (table_name_id);


--
-- Name: invoice_tablename_company_id_98af6ba0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX invoice_tablename_company_id_98af6ba0 ON public.invoice_tablename USING btree (company_id);


--
-- Name: table_data_gin_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX table_data_gin_idx ON public.invoice_tabledata USING gin (table_data);


--
-- Name: table_metadata_gin_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX table_metadata_gin_idx ON public.invoice_tablemetadata USING gin (table_metadata);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_invoice_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_invoice_customuser_id FOREIGN KEY (user_id) REFERENCES public.invoice_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_customuser invoice_customuser_company_id_73c4c12b_fk_invoice_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser
    ADD CONSTRAINT invoice_customuser_company_id_73c4c12b_fk_invoice_company_id FOREIGN KEY (company_id) REFERENCES public.invoice_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_customuser_groups invoice_customuser_g_customuser_id_369028c2_fk_invoice_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_groups
    ADD CONSTRAINT invoice_customuser_g_customuser_id_369028c2_fk_invoice_c FOREIGN KEY (customuser_id) REFERENCES public.invoice_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_customuser_groups invoice_customuser_groups_group_id_d90819a4_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_groups
    ADD CONSTRAINT invoice_customuser_groups_group_id_d90819a4_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_customuser_user_permissions invoice_customuser_u_customuser_id_14ed4fcc_fk_invoice_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_user_permissions
    ADD CONSTRAINT invoice_customuser_u_customuser_id_14ed4fcc_fk_invoice_c FOREIGN KEY (customuser_id) REFERENCES public.invoice_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_customuser_user_permissions invoice_customuser_u_permission_id_a94c7860_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_customuser_user_permissions
    ADD CONSTRAINT invoice_customuser_u_permission_id_a94c7860_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_form invoice_form_company_id_4ada5fcd_fk_invoice_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form
    ADD CONSTRAINT invoice_form_company_id_4ada5fcd_fk_invoice_company_id FOREIGN KEY (company_id) REFERENCES public.invoice_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_form_group invoice_form_group_form_id_fac11931_fk_invoice_form_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_group
    ADD CONSTRAINT invoice_form_group_form_id_fac11931_fk_invoice_form_id FOREIGN KEY (form_id) REFERENCES public.invoice_form(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_form_group invoice_form_group_group_id_1ca5d9f1_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_group
    ADD CONSTRAINT invoice_form_group_group_id_1ca5d9f1_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_form_table invoice_form_table_form_id_1e30177e_fk_invoice_form_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_table
    ADD CONSTRAINT invoice_form_table_form_id_1e30177e_fk_invoice_form_id FOREIGN KEY (form_id) REFERENCES public.invoice_form(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_form_table invoice_form_table_tablename_id_a252126a_fk_invoice_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_form_table
    ADD CONSTRAINT invoice_form_table_tablename_id_a252126a_fk_invoice_t FOREIGN KEY (tablename_id) REFERENCES public.invoice_tablename(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_report invoice_report_company_id_07f257b0_fk_invoice_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report
    ADD CONSTRAINT invoice_report_company_id_07f257b0_fk_invoice_company_id FOREIGN KEY (company_id) REFERENCES public.invoice_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_report_group invoice_report_group_group_id_fa22ca7d_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_group
    ADD CONSTRAINT invoice_report_group_group_id_fa22ca7d_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_report_group invoice_report_group_report_id_98b15249_fk_invoice_report_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_group
    ADD CONSTRAINT invoice_report_group_report_id_98b15249_fk_invoice_report_id FOREIGN KEY (report_id) REFERENCES public.invoice_report(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_report_table invoice_report_table_report_id_f7d87d1e_fk_invoice_report_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_table
    ADD CONSTRAINT invoice_report_table_report_id_f7d87d1e_fk_invoice_report_id FOREIGN KEY (report_id) REFERENCES public.invoice_report(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_report_table invoice_report_table_tablename_id_6ab6dab9_fk_invoice_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_report_table
    ADD CONSTRAINT invoice_report_table_tablename_id_6ab6dab9_fk_invoice_t FOREIGN KEY (tablename_id) REFERENCES public.invoice_tablename(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_tabledata invoice_tabledata_company_id_c13f0549_fk_invoice_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tabledata
    ADD CONSTRAINT invoice_tabledata_company_id_c13f0549_fk_invoice_company_id FOREIGN KEY (company_id) REFERENCES public.invoice_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_tabledata invoice_tabledata_table_name_id_56bd5706_fk_invoice_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tabledata
    ADD CONSTRAINT invoice_tabledata_table_name_id_56bd5706_fk_invoice_t FOREIGN KEY (table_name_id) REFERENCES public.invoice_tablename(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_tablemetadata invoice_tablemetadat_table_name_id_025ada4e_fk_invoice_t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablemetadata
    ADD CONSTRAINT invoice_tablemetadat_table_name_id_025ada4e_fk_invoice_t FOREIGN KEY (table_name_id) REFERENCES public.invoice_tablename(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: invoice_tablename invoice_tablename_company_id_98af6ba0_fk_invoice_company_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_tablename
    ADD CONSTRAINT invoice_tablename_company_id_98af6ba0_fk_invoice_company_id FOREIGN KEY (company_id) REFERENCES public.invoice_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict bFnjweCAIxzbDExZ5kkcpIGfM1njrIhHjVraeFJckiMCvISz8xg5FAkGdCPlnTt

