# Generated by Django 5.2.10 on 2026-01-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempDP',
        ),
        migrations.DeleteModel(
            name='TempWeightSlip',
        ),
        migrations.DeleteModel(
            name='TWB',
        ),
    ]
