# Generated by Django 5.2.10 on 2026-02-23 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinvoice',
            name='deliveryat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tproduction',
            name='length_unit',
            field=models.ForeignKey(limit_choices_to={'unit_type__in': ['Length', '2']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tproduction_length_unit', to='invoice.munit'),
        ),
        migrations.AlterField(
            model_name='tproduction',
            name='weight_unit',
            field=models.ForeignKey(limit_choices_to={'unit_type__in': ['Weight', '1']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tproduction_weight_unit', to='invoice.munit'),
        ),
        migrations.AlterField(
            model_name='tproductionreel',
            name='productionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productionreels', to='invoice.tproduction'),
        ),
        migrations.CreateModel(
            name='TInvoiceDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoicedetailsid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoiceid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='invoice.tinvoice')),
                ('itemid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.mitem')),
                ('productionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_details', to='invoice.tproduction')),
                ('productionreelid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_reel_details', to='invoice.tproductionreel')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_by'], name='invoice_tin_created_33ef48_idx'), models.Index(fields=['updated_by'], name='invoice_tin_updated_5151ea_idx'), models.Index(fields=['created_at'], name='invoice_tin_created_1aca3b_idx'), models.Index(fields=['updated_at'], name='invoice_tin_updated_9fc869_idx')],
            },
        ),
    ]
