# Generated by Django 4.2.19 on 2025-05-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabledata",
            name="table_data",
            field=models.JSONField(blank=True, default=dict, null=True, unique=True),
        ),
    ]
