# Generated by Django 4.2.19 on 2025-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField()),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("userCompany", models.CharField()),
                ("userLog", models.JSONField(null=True)),
                ("userAccess", models.JSONField(null=True)),
            ],
            options={
                "permissions": [
                    ("create user", "can create user"),
                    ("edit user", "can edit user"),
                    ("delete user", "can delete user"),
                    ("set is_active", "can set is_active"),
                ],
            },
        ),
    ]
