# Generated by Django 5.2.10 on 2026-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tproduction',
            name='noofream',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tproduction',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tproduction',
            name='reamwt',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tproduction',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
