# Generated by Django 5.2.10 on 2026-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_tinvoice_deliveryat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='invoiceid',
        ),
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='productionid',
        ),
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='productionreelid',
        ),
        migrations.RemoveField(
            model_name='tinvoicedetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='texportdetails',
            name='invoicedate',
        ),
        migrations.RemoveField(
            model_name='texportdetails',
            name='invoiceid',
        ),
        migrations.RemoveField(
            model_name='texportdetails',
            name='invoiceno',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='munit',
            name='conversion_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tinvoice',
            name='productionid',
            field=models.ManyToManyField(null=True, related_name='invoices', to='invoice.tproduction'),
        ),
        migrations.AlterField(
            model_name='magent',
            name='agentname',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcustomer',
            name='custcode',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mcustomer',
            name='custname',
            field=models.CharField(db_index=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='mitem',
            name='itemcode',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mitemcategory',
            name='cat',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mlocation',
            name='location',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mshade',
            name='shadecode',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='tablename',
            index=models.Index(fields=['table_name'], name='tablename_table_name_idx'),
        ),
        migrations.AddIndex(
            model_name='texportdetails',
            index=models.Index(fields=['exportid'], name='texportdetails_export_idx'),
        ),
        migrations.AddIndex(
            model_name='tinvoice',
            index=models.Index(fields=['invoiceno'], name='tinvoice_invoiceno_idx'),
        ),
        migrations.AddIndex(
            model_name='tinvoice',
            index=models.Index(fields=['invoicedate'], name='tinvoice_invoicedate_idx'),
        ),
        migrations.AddIndex(
            model_name='tproduction',
            index=models.Index(fields=['rdate'], name='tproduction_rdate_idx'),
        ),
        migrations.AddIndex(
            model_name='tproduction',
            index=models.Index(fields=['stk'], name='tproduction_stk_idx'),
        ),
        migrations.AddIndex(
            model_name='tproduction',
            index=models.Index(fields=['approved'], name='tproduction_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='tproduction',
            index=models.Index(fields=['custid', 'stk'], name='tproduction_custid_stk_idx'),
        ),
        migrations.AddIndex(
            model_name='tproduction',
            index=models.Index(fields=['agentid', 'stk'], name='tproduction_agentid_stk_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['created_by'], name='invoice_tpr_created_b73734_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['updated_by'], name='invoice_tpr_updated_840364_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['created_at'], name='invoice_tpr_created_717b33_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['updated_at'], name='invoice_tpr_updated_17ce1c_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['reelno'], name='tproductionreel_reelno_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['productionid', 'reelno'], name='tproductionreel_prod_reel_idx'),
        ),
        migrations.AddIndex(
            model_name='tproductionreel',
            index=models.Index(fields=['stkdate'], name='tproductionreel_stkdate_idx'),
        ),
        migrations.DeleteModel(
            name='TInvoiceDetails',
        ),
    ]
