# Generated by Django 5.2.10 on 2026-03-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_tproduction_noofream_alter_tproduction_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magent',
            old_name='bname',
            new_name='branch_name',
        ),
        migrations.RemoveField(
            model_name='magent',
            name='division',
        ),
        migrations.RemoveField(
            model_name='magent',
            name='range',
        ),
    ]
