# Generated by Django 5.2.6 on 2025-11-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_template_alter_customuser_user_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tabledata',
            name='unique_table_data_name_company',
        ),
        migrations.AddField(
            model_name='tabledata',
            name='json_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tablemetadata',
            name='table_unique',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='table_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='table data'),
        ),
    ]
