# Generated by Django 4.2.21 on 2025-06-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_tabledata_table_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabledata",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoice.company",
            ),
            preserve_default=False,
        ),
    ]
