# Generated by Django 4.2.21 on 2025-06-12 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_tabledata_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="group",
        ),
    ]
