# Generated by Django 5.2.6 on 2025-12-27 09:47

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_tabledata_unique_table_data_name_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='tabledata',
            name='table_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='table data'),
        ),
        migrations.AlterField(
            model_name='tablemetadata',
            name='table_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, unique=True, verbose_name='table metadata'),
        ),
    ]
