# Generated by Django 5.2.10 on 2026-03-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_rename_bname_magent_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mexportfields',
            old_name='descriptiongoods',
            new_name='description_of_goods',
        ),
        migrations.RenameField(
            model_name='mexportfields',
            old_name='hsno',
            new_name='hs_no',
        ),
        migrations.RenameField(
            model_name='mexportfields',
            old_name='declaration',
            new_name='tax_declaration',
        ),
        migrations.RemoveField(
            model_name='mcustomer',
            name='custcode',
        ),
        migrations.RemoveField(
            model_name='mexportfields',
            name='compcode',
        ),
        migrations.AddField(
            model_name='mexportfields',
            name='company_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company'),
        ),
    ]
