# Generated by Django 4.2.21 on 2025-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_remove_customuser_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablename",
            name="table_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="tabledata",
            constraint=models.UniqueConstraint(
                fields=("table_data", "table_name", "company"),
                name="unique_table_data_table_name_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablename",
            constraint=models.UniqueConstraint(
                fields=("table_name", "company"), name="unique_table_name_company"
            ),
        ),
    ]
