# Generated by Django 5.2.10 on 2026-01-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_report_report_data_alter_tabledata_table_data_and_more'),
        ('invoice', '0004_magent_mcategory_mcompany_mcustomer_memployee_and_more'),
    ]

    operations = [
    ]
