# Generated by Django 4.2.23 on 2025-08-02 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_alter_tablename_table_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelOptions(
            name="tabledata",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="tablename",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="company name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="invoice.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_emp_code",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Employee Code"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(max_length=255, verbose_name="User Name"),
        ),
        migrations.AlterField(
            model_name="tabledata",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table_data",
                to="invoice.company",
            ),
        ),
        migrations.AlterField(
            model_name="tabledata",
            name="table_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                unique=True,
                verbose_name="table data",
            ),
        ),
        migrations.AlterField(
            model_name="tabledata",
            name="table_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_rows",
                to="invoice.tablename",
            ),
        ),
        migrations.AlterField(
            model_name="tablename",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="invoice.company",
            ),
        ),
        migrations.AlterField(
            model_name="tablename",
            name="table_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="table name"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["user_emp_code"], name="invoice_cus_user_em_161fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="invoice_cus_email_9d532c_idx"),
        ),
    ]
