# Generated by Django 4.2.19 on 2025-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_customuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="email address"),
        ),
    ]
