# Generated by Django 4.2.19 on 2025-02-13 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="table_permission",
        ),
    ]
