# Generated by Django 4.2.19 on 2025-02-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("invoice", "0003_remove_table_table_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="group",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
