# Generated by Django 4.2.19 on 2025-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0004_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_data",
            field=models.JSONField(default=list, null=True),
        ),
    ]
