# Generated by Django 4.2.19 on 2025-02-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("invoice", "0004_customuser_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="user",
        ),
        migrations.AddField(
            model_name="form",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
    ]
