# Generated by Django 4.2.19 on 2025-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("invoice", "0005_remove_form_user_form_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={
                "permissions": [
                    ("edit_form", "can edit form"),
                    ("access_form", "can access form"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="form",
            name="group",
        ),
        migrations.AddField(
            model_name="form",
            name="group",
            field=models.ManyToManyField(null=True, to="auth.group"),
        ),
    ]
