# Generated by Django 4.2.19 on 2025-03-22 09:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_alter_table_table_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="form",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["form_data"], name="form_data_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["report_data"], name="report_data_gin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["table_data"], name="table_data_gin_idx"
            ),
        ),
    ]
