# Generated by Django 4.2.19 on 2025-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0006_form_form_data_gin_idx_report_report_data_gin_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="form",
            name="form_data_gin_idx",
        ),
        migrations.RemoveIndex(
            model_name="report",
            name="report_data_gin_idx",
        ),
        migrations.AddField(
            model_name="table",
            name="table_data_columns",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_name",
            field=models.CharField(unique=True),
        ),
    ]
