# Generated by Django 4.2.19 on 2025-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0007_remove_form_form_data_gin_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_data_columns",
            field=models.CharField(null=True),
        ),
    ]
