# Generated by Django 4.2.19 on 2025-03-26 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0008_alter_table_table_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="table_data_columns",
        ),
    ]
