# Generated by Django 4.2.19 on 2025-05-02 05:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0009_remove_table_table_data_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_data",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), size=None
            ),
        ),
    ]
