# Generated by Django 4.2.19 on 2025-05-02 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0010_alter_table_table_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_data",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), size=1000
            ),
        ),
    ]
